# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/dn/Nexys-A7-100T-Master.xdc

# IP: ip/ClkGen/ClkGen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] -quiet

# XDC: c:/Users/Lazar/OneDrive/Desktop/1. semestar 3. letnik/dn/project/project/project.gen/sources_1/ip/ClkGen/ClkGen_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Lazar/OneDrive/Desktop/1. semestar 3. letnik/dn/project/project/project.gen/sources_1/ip/ClkGen/ClkGen.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Lazar/OneDrive/Desktop/1. semestar 3. letnik/dn/project/project/project.gen/sources_1/ip/ClkGen/ClkGen_ooc.xdc
